#!/bin/bash

BROWSER=chrome

# look for possible browser from the command line
if [ "$#" -eq 1 ]; then
    BROWSER=$1
fi

# create the working directory
mkdir scratch
pushd scratch
mkdir $BROWSER
pushd $BROWSER

# copy relevant files into the working directory
cp ../../cinema_module.ipynb .
cp -rf ../../data .
cp -rf ../../cinemasci .

# run jupyter with the requested browser
jupyter-3.7 notebook --browser=$BROWSER
