#!/bin/bash

BROWSER=chrome

if [ "$#" -eq 1 ]; then
    BROWSER=$1
fi

mkdir scratch
pushd scratch
mkdir $BROWSER
pushd $BROWSER
cp ../../cinema_module.ipynb .
cp -rf ../../data .
cp -rf ../../cinemasci .
jupyter-3.7 notebook --browser=$BROWSER
